name: test files
on: [push]
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install dependencies
        run: npm install
      - name: Tests
        run: npm test
      - name: Create docker image
        run: docker build . -t nuxt-docker
      - run: docker tag nuxt-docker ghcr.io/nvcq/nuxt-docker:1.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - run: docker push ghcr.io/nvcq/nuxt-docker:1.0.0 
